name=SoftServo
version=2.0.3
author=AlexGyver <alex@alexgyver.ru>
maintainer=AlexGyver <alex@alexgyver.ru>
sentence=Library for software servo motor control
paragraph=Library for software servo motor control
category=Device Control
url=https://github.com/GyverLibs/SoftServo
architectures=*